microg/GmsCore

- Android.mk
The current Android.mk build is broken, so I call gradle internally to get a working build.
> Android.mk build using gradle

- play-services-core/src/main/res/values-pl/strings.xml
Just initial translation to Polish
> Include initial Polish translation

- play-services-core/src/main/res/values-de/strings.xml
Since there are already Serbian and Romanian translations, here is one translation I can provide.
I think you are a native German speaker, too. So you might want to change a few things :wink:
> Add German translation

- README.md
Added info from the XDA thread and issues to make it more accessible to new users. Instead of copying sections which already exist, I added links to the XDA thread where appropriate. Also, the copyright was updated.
> Update README with info from XDA and issues

- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
This changes how the heartbeat ping is scheduled in order to have a guaranteed maximum time that passes between two heartbeat pings. Further the connection is considered to be dead when no acknowledgment has been received for twice the configured interval.
In my experience the previously used repeating alarm can be delayed as much as 15 minutes, after that time the connection is gone on my phone. With these changes I get a stable connection for at least 8 hours when configuring the interval to be 5 minutes (which results in intervals between 2.5 and 5 minutes in order to give the OS a bit flexibility concerning battery-friendly scheduling) both via WiFi and UMTS.
What I haven't tested is the behavior below KitKat (which should use a different method) and I'm relatively sure that this is …
> GCM: Make heartbeat more stable

- README.md
Fixes #78. The XDA thread should be updated accordingly.
> Move README to wiki

- patches/android_frameworks_base-M.patch
Previous patch do not apply with git apply.
This one is generated with git format-patch, and can be applied with git am.
> Update patch to be compatible with git am on Android M

- play-services-core/src/main/res/values-fr/strings.xml
This definitively not perfect (a lot of technical terms currently don’t have good equivalents in french to my knowledge), but better than nothing. ;)
> Add French translation

- play-services-core/src/main/res/values-ru/permissions.xml
- play-services-core/src/main/res/values-ru/strings.xml
I just added Russian translation :)
> Added Russian translation

- play-services-core/src/main/res/values-zh-rTW/permissions.xml
- play-services-core/src/main/res/values-zh-rTW/strings.xml
> Add Chinese(Taiwan) Translation.

- play-services-core/src/main/res/values-ru/strings.xml
Translated new strings and minor translation fixes.
> Update russian translation

- Android.mk
Takes into account if compiling a debug build.
> Changed OUT_DIR to TARGET_COMMON_OUT_ROOT

- play-services-core/src/main/res/values-ru/strings.xml
> Russian translation

- play-services-core/src/main/res/values-pl/strings.xml
Fixed translation (stylistic and grammatical errors, missing strings etc). 
Now the translation is more understandable and makes more sense.
> Update polish translation

- play-services-core/src/main/res/values-pl/plurals.xml
Fixed translation (stylistic errors) - plurals.xml
> Update polish translation part 2

- play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java
This fixes issue https://github.com/microg/android_packages_apps_GmsCore/issues/484
> Add signature for the google daydream app

- play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java
> Show UI on retrieveRtToken() error

- play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java
Fixes for the login screen issue ("Login" button not clickable) by @PorygonZRocks - reportedly works.
(I know it's not common for a thirdparty to send in a pull request, but still)
> Add version check to skip first screen on KK (login fix)

- play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java
As per user-report [on twitter](https://twitter.com/JainendraNahata/status/1046463141184303105) that's all that is required to make Wellbeing work with microG.
> add Wellbeing to KNOWN_GOOGLE_PACKAGES

- play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java
- Google Crowdsource #798 
- Google One #806
> Add new KNOWN_GOOGLE_PACKAGES (fix #798, #806)

- play-services-core/microg-ui-tools/src/main/res/values-it/strings.xml
- play-services-core/src/main/res/values-it/permissions.xml
- play-services-core/src/main/res/values-it/plurals.xml
- play-services-core/src/main/res/values-it/strings.xml
Not a real coder but a microG user that want to thank you for this project in its small way. I added translated strings for IT localization, hope there are not missing files or other things to be added, in that case, please, let me know.
Sorry for the inconvenience with the request, hope everything is fixed now.
> Added IT lang files

- play-services-base/src/main/AndroidManifest.xml
Move <meta-data> inside <application>. Fixes #1122.
> Fix for #1122

- play-services-core/src/main/java/com/google/android/gms/chimera/container/DynamiteLoaderImpl.java
Return v1 for maps. Fixes #1124.
> Fix for #1124

- play-services-api/src/main/aidl/com/google/android/gms/maps/internal/IGoogleMapDelegate.aidl
- play-services-api/src/main/aidl/com/google/android/gms/maps/model/MapStyleOptions.aidl
- play-services-api/src/main/java/com/google/android/gms/maps/model/MapStyleOptions.java
- play-services-location-api/src/main/java/com/google/android/gms/location/internal/LocationRequestInternal.java
- play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
- play-services-maps-core-vtm/src/main/java/org/microg/gms/maps/vtm/GoogleMapImpl.java
Don't null a param which is still used, stub for missing function. Fixes #1126.
> Fix for #1126

- play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
Allow null bitmap. Fixes #1128.
> Fix for #1128

- play-services-core/microg-ui-tools/src/main/res/values-de/strings.xml
- play-services-core/src/main/res/values-de/plurals.xml
- play-services-core/src/main/res/values-de/strings.xml
This pull request contains a commit that adds some more German translations.
Furthermore, some typos in the current translation were fixed.
In case you have other translation proposals we can discuss them, of course.
> Improve German translation

- play-services-basement/src/main/java/com/google/android/gms/common/api/ApiException.java
- play-services-basement/src/main/java/com/google/android/gms/common/api/ResolvableApiException.java
- play-services-nearby-api/src/main/java/com/google/android/gms/nearby/exposurenotification/TemporaryExposureKey.java
- play-services-nearby-api/src/main/java/com/google/android/gms/nearby/exposurenotification/internal/ProvideDiagnosisKeysParams.java
- play-services-nearby/src/main/java/org/microg/gms/nearby/ExposureNotificationClientImpl.java
Updates to the EN client library, implemented as part of #1179.
Still WiP so far, as not everything has been tested.
> Updates to EN client library

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/AdvertiserService.kt
- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ScannerService.kt
This PR changes the DB accesses in the Advertiser and Scanner services to be uniform with the way they are done in the ExposureNotification service.
Appears to fix #1200
> EN: Make DB access uniform with ENServiceImpl

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureNotificationServiceImpl.kt
> Add exposure summary to exposure intent

- play-services-nearby-api/src/main/java/com/google/android/gms/nearby/exposurenotification/DiagnosisKeyFileProvider.java
- play-services-nearby-api/src/main/java/com/google/android/gms/nearby/exposurenotification/ExposureConfiguration.java
- play-services-nearby-api/src/main/java/com/google/android/gms/nearby/exposurenotification/ExposureInformation.java
- play-services-nearby-api/src/main/java/com/google/android/gms/nearby/exposurenotification/ExposureNotificationStatusCodes.java
- play-services-nearby-api/src/main/java/com/google/android/gms/nearby/exposurenotification/ExposureSummary.java
- play-services-nearby-api/src/main/java/com/google/android/gms/nearby/exposurenotification/TemporaryExposureKey.java
- play-services-nearby-api/src/main/java/org/microg/gms/nearby/exposurenotification/Constants.java
- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureNotificationServiceImpl.kt
- play-services-nearby/src/main/java/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient.java
- play-services-nearby/src/main/java/org/microg/gms/nearby/ExposureNotificationApiClient.java
- play-services-nearby/src/main/java/org/microg/gms/nearby/ExposureNotificationClientImpl.java
Work in progress, do not pull yet.
> Add methods to client library

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureNotificationServiceImpl.kt
Just for safety :) , as done in https://github.com/microg/GmsCore/commit/4c2ef04364691b04aace378415b9a85c011829d3#diff-c5269f84cb5abc7cdcf027bfb5266500a8cb8695db11df6233e960500837cfeeR308
> EN: Avoid division by 0

- play-services-base-core-ui/src/main/res/values-ja/strings.xml
- play-services-core/microg-ui-tools/src/main/res/values-ja/strings.xml
- play-services-core/src/main/res/values-ja/permissions.xml
- play-services-core/src/main/res/values-ja/plurals.xml
- play-services-core/src/main/res/values-ja/strings.xml
I wrote a Japanese Translation.
Can you tell me if there are any necessary corrections?
I'm a microG user and I'm very grateful for your work.
> Add Japanese Translation

- play-services-nearby-core-ui/src/main/res/values-it/strings.xml
> Fixed typos

- play-services-base-core/src/main/res/values-be/strings.xml
- play-services-base-core/src/main/res/values-ru/strings.xml
- play-services-core/src/main/res/values-be/strings.xml
- play-services-core/src/main/res/values-ru/strings.xml
- play-services-nearby-core-ui/src/main/res/values-be/strings.xml
- play-services-nearby-core-ui/src/main/res/values-ru/strings.xml
- add new strings
- fix some old strings
> Improve translations

- play-services-core/src/main/kotlin/org/microg/gms/provision/ProvisionService.kt
Change-Id: I518f54653791ce02cb0e82662802474c5e8852d5
> Replace remaining shared preference edits with service configuration setters

- play-services-base-core/src/main/java/org/microg/gms/common/PackageUtils.java
Android Auto crashes on startup, Whitelisting it seems to fix it
> Add Android Auto to known Google packages

- play-services-core/src/main/res/values/strings.xml
> Correct grammar

- play-services-core/src/main/AndroidManifest.xml
* Should help with not having services killed
* System app only, but shouldn't cause any errors if it's a user-app
> Make the application persistent

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/org/microg/gms/fonts/FontsProvider.kt
> Add a FontsProvider that always returns the default font

- play-services-core/src/main/kotlin/org/microg/gms/settings/SettingsProvider.kt
* This is really spammy!
Change-Id: If1b9cbaa50bf8af37ca7146c6f510ad6875bab35
> SettingsProvider: Remove logs

- play-services-base-core/src/main/java/org/microg/gms/common/PackageUtils.java
Change-Id: Ie70cde85e398dc5eed13fc2294f78088661a743a
> Add Stadia to known Google packages

- play-services-core/microg-ui-tools/src/main/res/layout/app_bar.xml
- play-services-core/microg-ui-tools/src/main/res/layout/switch_bar.xml
Closes: #267 , #463 .
This is the same fix made by emv412 here: https://github.com/microg/android_external_MicroGUiTools/pull/11
> Fix UI crash in Asus 5.0 devices

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureNotificationServiceImpl.kt
> [EN] Verify keyfiles signatures

- play-services-core/src/main/java/org/microg/gms/checkin/TriggerReceiver.java
- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
- play-services-core/src/main/java/org/microg/gms/gcm/TriggerReceiver.java
- play-services-core/src/main/kotlin/org/microg/gms/gcm/GcmPrefs.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/SettingsFragment.kt
When visiting settings UI and one is not checked in, this will also cause a check-in to be performed (if enabled). In case internet is missing when check-in is attempted, it will be retried once internet is back.
> Fix some push issues by adjusting heartbeat interval

- build.gradle
This should potentially fix apps asking for the newest Play Services version.
> Bump GMS version to 21.45.16

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureDatabase.kt
At first I thought this might need a bigger solution but looking at it again, it really only needs changes in the Database class.
Fixes #1633.
> Add missing fields to ENF database

- play-services-nearby-core/src/main/AndroidManifest.xml
- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/AdvertiserService.kt
- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/CleanupService.kt
- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureNotificationServiceImpl.kt
- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/NotifyService.kt
- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ScannerService.kt
This is required to build CCTG with Android 12: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/176
> Fix EN with `targetSdk` 31

- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
The new method only gets used on Android 12 and above.
See: https: //cs.android.com/android/_/android/platform/frameworks/base/+/1aa89de1cfec5b7c1197d2f6c2b33dffda8bd3f5
> Use new method for lifting idle restrictions temporarily when receiving PUSH messages

- play-services-core/src/main/res/values-zh-rCN/plurals.xml
- play-services-core/src/main/res/values-zh-rCN/strings.xml
- play-services-core/src/main/res/values/strings.xml
- play-services-core/src/main/res/xml/preferences_device_registration.xml
- Translated these strings into Simplified Chinese
- Adjusted several previous translations.
> Make several strings translatable

- build.gradle
This will save us from update messages for a while :)
> Bump GMS version to 22.33.15

- play-services-base-core/src/main/java/org/microg/gms/common/PackageUtils.java
> Add Google Family Link to known Google packages

- build.gradle
> Bump GMS version to 22.36.16

- play-services-core/src/main/kotlin/org/microg/gms/ui/PushNotificationPreferencesFragment.kt
It need testing but the fix is similar to the one from @grote so it shouldn't cause any issue.
> Workaround context crashes, fixes #1653

- play-services-core/src/main/kotlin/org/microg/gms/ui/SafetyNetAppPreferencesFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/SafetyNetUtils.kt
- play-services-core/src/main/res/values-it/strings.xml
- play-services-core/src/main/res/values/strings.xml
- play-services-droidguard/core/src/main/res/values-it/strings.xml
- play-services-nearby/core/src/main/res/values-it/strings.xml
- play-services-oss-licenses/src/main/res/values-it/strings.xml
- play-services-oss-licenses/src/main/res/values/strings.xml
This is a follow-up to #1860 to update the Italian translation and (again) slightly improve localization for the SafetyNet UI.
I've also translated the UI strings for the oss-licenses module ~~(which had a couple of unused strings btw)~~.
> Update Italian translations

- play-services-maps-core-mapbox/build.gradle
- play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
Fixes https://github.com/microg/GmsCore/issues/1463.
> Use MapLibre

- play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
Sync latest /e/ fixes:
* https://gitlab.e.foundation/e/os/GmsCore/-/merge_requests/77
* https://gitlab.e.foundation/e/os/GmsCore/-/merge_requests/79
> Initialization regression fixes

- artwork/styles/style-microg-normal-openmaptiles.json
- artwork/styles/style-microg-normal-stadia.json
- artwork/styles/style-microg-satellite-stadia.json
- play-services-maps-core-mapbox/src/main/assets/style-microg-normal-stadia.json
- play-services-maps-core-mapbox/src/main/assets/style-microg-satellite-stadia.json
* Show more POI
* Show railway (re. https://github.com/openmaptiles/openmaptiles/issues/1578)
Brief test in emulator (with the usual emulator rendering bugs):
---|---
> Fix bugs in new styles

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/res/values/strings.xml
Declare com.google.android.providers.gsf.permission.READ_GSERVICES permission, fix #1366
> Declare com.google.android.providers.gsf.permission.READ_GSERVICES permission, fix #1366

- artwork/styles/style-microg-normal-openmaptiles.json
- artwork/styles/style-microg-normal-stadia.json
- artwork/styles/style-microg-satellite-stadia.json
- play-services-maps/core/mapbox/src/main/assets/style-microg-normal-stadia.json
- play-services-maps/core/mapbox/src/main/assets/style-microg-satellite-stadia.json
Contains https://gitlab.e.foundation/e/os/GmsCore/-/merge_requests/90.
> Sync e fixes

- play-services-fido/core/src/main/AndroidManifest.xml
Fixes passkey creation
Change-Id: I49c97ad820be35dec1f32944361b4e3b617c1d0f
> Fido: Allow background activity launch

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/utils/typeConverter.kt
fixed <real-time weather> & <Meteoroloji> app map layer display issues
> Fix issues with ground overlay in HMS maps

- play-services-appset/core/src/main/kotlin/org/microg/gms/appset/AppSetService.kt
open App crash  eg:CallApp、webtoon、Parallel Space
> Return proper dummy value in AppSetService.getAppSetIdInfo

- play-services-core/src/main/kotlin/org/microg/gms/auth/credentials/identity/IdentitySignInService.kt
Fix the problem of not being able to log in to Google through the IDENTITY_SIGN_IN service。e.g. IQ Option – Trading Platform
> Fix the problem of being unable to log in

- play-services-location/src/main/java/com/google/android/gms/location/DeviceOrientation.java
…ve number, the arrow will not rotate with the rotation.
log:
```
2024-02-29 15:53:12.425  9069-9098  Binder                          com.google.android.apps.maps         W  Caught a RuntimeException from the binder stub implementation.
java.lang.IllegalArgumentException
at a.ay(PG:1)
at com.google.android.gms.location.DeviceOrientation.<init>(PG:2)
at axin.createFromParcel(PG:49)
at imn.a(PG:2)
at axpc.dispatchTransaction(PG:1)
at imm.onTransact(PG:2)
at android.os.Binder.execTransactInternal(Binder.java:1191)
at android.os.Binder.execTransact(Binder.java:1150)
2024-02-29 15:53:12.509  9069-9172  Binder                          com.google.android.apps.maps         W  Caught a RuntimeException from the binder stub implementation.
java.lang.IllegalArgumentException
at a.ay(PG:1)
at …
```
> DeviceOrientation: correctly handle all degree values

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/org/microg/gms/backup/BackupSettingsActivity.kt
- play-services-core/src/main/kotlin/org/microg/gms/backup/component/BackupSettingsCollapsingActivity.kt
- play-services-core/src/main/res/values-zh-rCN/strings.xml
- play-services-core/src/main/res/values/strings.xml
Fix jump to backup and repair page crash exception. 
e.g.  Google Drive
> Add dummy for ACTION_BACKUP_SETTINGS

- play-services-basement/src/main/java/org/microg/gms/common/GmsService.java
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/AuthSignInActivity.kt
Resolved the issue preventing the game from logging in.
e.g. Clash of Clans  &  Brawl Stars
> Games: Resolved the issue preventing some games from logging in

- play-services-location/core/provider/src/main/kotlin/org/microg/gms/location/network/cell/CellDetailsSource.kt
Fix exceptions in CellDetailsSource when the ACCESS_FINE_LOCATION permission isn't granted.
Should fix #2213
> Fix exceptions in CellDetailsSource when the ACCESS_FINE_LOCATION permission isn't granted

- play-services-basement/src/main/java/org/microg/gms/common/GmsService.java
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/org/microg/gms/chimera/ServiceProvider.kt
Due to the following modification, some services that have not been implemented or declared have problems. What is currently known is that the messager cannot display data after entering the homepage and keeps loading.
https://github.com/microg/GmsCore/commit/64307c1c194d21f5794a5d8789ecdd280b301e7d
> Chimera: Fix connection to unsupported services

- play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java
Fix the problem of being unable to connect to a Google account
e.g. Google Contact
> Auth: Make account visible after creation when configured to do so

- play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java
…e, it still stays on the login page after logging in.
> Auth: Return result from login activity

- .github/workflows/build.yml
> Separate assemble and check on GitHub workflow to make the nature of the issue easier to see

- play-services-api/src/main/java/com/google/android/gms/measurement/internal/AppMetadata.java
- play-services-basement/src/main/java/org/microg/gms/auth/AuthConstants.java
- play-services-core/src/main/java/org/microg/gms/auth/AuthManagerServiceImpl.java
- play-services-core/src/main/kotlin/org/microg/gms/measurement/MeasurementService.kt
- play-services-core/src/main/res/layout/login_assistant.xml
- play-services-core/src/main/res/layout/signin_confirm.xml
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/Projection.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/model/Marker.kt
- play-services-maps/core/mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/utils/MapContext.kt
- play-services-recaptcha/core/src/main/kotlin/org/microg/gms/recaptcha/RecaptchaWebImpl.kt
1. fixed the exception login issue caused by the AppInstanceId being null
2. fixed skype app crash
3. fixed the issue that the HKTaxi app could not move when selecting a location
4. fixed the issue where marker information is not displayed on the KMB.LWB app map
5. fixed the crash exception when clicking the icon in the lower left corner of the mapbox map pop-up window content page to jump
6. fixed the problem that Claro Flex APP cannot enter the application
7. fixed the problem that Chai - Chat with AI Friends cannot log in using google
8. fixed the problem that the background of the authorization login page is transparent and the horizontal screen display is incomplete and cannot be slid.
9. fixed the problem that the horizontal screen title of the login page is blocked
> Fixed some issues

- play-services-core/src/main/kotlin/org/microg/gms/games/GamesService.kt
- play-services-core/src/main/kotlin/org/microg/gms/games/extensions.kt
Fix the problem that game applications cannot log in normally。
e.g. War Thunder Mobile
> Games Login: Get true range via GAMES or GAMES_LITE

- play-services-safetynet/src/main/java/com/google/android/gms/safetynet/SafetyNetApi.java
- play-services-safetynet/src/main/java/com/google/android/gms/safetynet/SafetyNetClient.java
- play-services-safetynet/src/main/java/org/microg/gms/safetynet/SafetyNetGmsClient.java
Seems like SafetyNet wasn't fully implemented
> feat(SafetyNet): publicly expose Verify Apps API

- .github/workflows/build.yml
This update also the "position" since the action was moved.
The old position still works but it may be removed in the future.
> Update Gradle Wrapper validation action

- play-services-location/src/main/java/org/microg/gms/location/FusedLocationProviderClientImpl.java
> Location: implement FusedLocationProviderClient.getLocationAvailability

- play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java
login: Fixed the issue where some apps would display a white screen when Cancel logging in.
Cancel if there is no Google account on the device.
e.g. Google Drive
> login: Fixed the issue where some apps would display a white screen 

- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/extensions.kt
The buildPermKey() method is related to TokenRequestOptions and needs to be set later.
> Auth: isPermitted position adjustment

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/Projection.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/UiSettings.kt
1. Avoid NullPointerExceptions when some applications call map information.
2. Sometimes fakeWatermark does not work, and in the Skype app it is found that a black screen occurs when operating in OnGlobalLayoutListener.
> HmsMap:Improve default information & Optimize fakeWatermark logic

- play-services-core/src/main/kotlin/org/microg/gms/auth/credentials/CredentialsService.kt
Found that some applications cannot be logged in normally.
e.g. Pinterest_12.16.0
> Auth: update credentials feature version

- play-services-location/core/src/main/AndroidManifest.xml
- play-services-location/core/src/main/kotlin/org/microg/gms/location/settings/GoogleLocationSettingsActivity.kt
fix Google maps Cannot open Google location setting on Google maps
> Add Google redirect location settings page

- play-services-recaptcha/core/src/main/kotlin/org/microg/gms/recaptcha/RecaptchaService.kt
During application testing, it was discovered that some references could not complete the process through RecaptchaWebImpl, but could be processed through RecaptchaGuardImpl. So it is made into a collection here. If there is an initialization exception, it can be handled through the next one. If all initialization fails, an exception will be returned.
e.g.  Coursera-5.3.0
> Recaptcha: Improve RecaptchaImpl

- play-services-core/src/main/kotlin/org/microg/gms/languageprofile/LanguageProfileService.kt
Fixed the issue that some accounts were prompted to update GMS in Google Maps
> language profile service add features

- firebase-auth/build.gradle
- firebase-auth/core/src/main/kotlin/org/microg/gms/firebase/auth/FirebaseAuthService.kt
- firebase-auth/core/src/main/kotlin/org/microg/gms/firebase/auth/IdentityToolkitClient.kt
- firebase-auth/src/main/java/com/google/firebase/auth/api/internal/SignInWithCredentialAidlRequest.java
- firebase-auth/src/main/java/com/google/firebase/auth/api/internal/VerifyAssertionRequest.java
Fixed the issue that the app cannot log in.
e.g. King James Bible <kjv.bible.kingjamesbible>
> FirebaseAuth: Improve signInWithCredential

- play-services-core/src/main/java/org/microg/gms/wallet/PaymentService.java
TEMU<com.einnovation.temu> App notifies you that you need to update GMS when you are using it
> Add features to PaymentService

- vending-app/src/main/java/org/microg/vending/billing/core/IAPCore.kt
- vending-app/src/main/proto/GooglePlay.proto
Fixed the problem of getting sku using SKU_SERIALIZED_DOCID_LIST parameter. For example, the latest version of google tv purchase
> IAP: Add support for "SKU_SERIALIZED_DOCID_LIST"

- play-services-core/src/main/kotlin/org/microg/gms/auth/credentials/identity/IdentitySignInService.kt
Fixed the issue that the quick login page flickers when there is no account
> Auth: Fix login page flickering when there is no account

- build.gradle
> Bump GMS version to 24.47.35

- TRANSLATION.md
Uses a special Markdown feature for showing the microG-UI-tools warning
Modifies some of the wording to be more user-friendly and thank Weblate for their hosting
---
Old:
New:
> TRANSLATION: Revamp page

- build.gradle
> Bump GMS version to 25.09.32

- play-services-core/src/main/kotlin/org/microg/gms/auth/consent/ConsentSignInActivity.kt
@mar-v-in
Sorry I'm a bit late but here is the PR.
> Complete the PR #2836

- play-services-core/src/main/kotlin/com/google/android/gms/measurement/internal/AppMeasurementDynamiteService.kt
Fix the app crash issue.
e.g. de.sec.mobile 
Step: Add optional items to the shopping cart.
> AppMeasurement: Added UserProperties record

- play-services-core/microg-ui-tools/src/main/res/values-zh-rCN/strings.xml
Add microg-ui-tools Simplified Chinese translations
> Add Simplified Chinese translations

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/model/Polyline.kt
Fix the anr problem when using bolt to take a taxi.
> HMSMap: Optimized PolylineImpl

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/MapFragment.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/MapView.kt
Test application:
1. ladeapp<de.ladenetz.app> Crashes when launching the map.
2. Rop<pkg.rop> Crashes when clicking on the map location.
> HMSMap: Handle more view access methods

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/UiSettings.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/utils/MapUiController.kt
Solve the problem of overlapping some application controls with map controls.
e.g. Gojek <com.gojek.app>
> HMSMap: Improve map control handling

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/utils/MapContext.kt
1. Map display errors in apps like taxi.eu, HK Sightseeing, and ROP.
2. Resolve exceptions caused by differences in map animation execution. e.g. Glovo: Food Delivery and More
> HMSMap: Fixed some abnormal scenes in the map
