microg/GmsCore

- Android.mk
Because of the internal use of gradle the Android buildsystem does not recognize file changes and only rebuilds GmsCore when the APK file is missing.
To allow a rebuild after `make clean` the build dir of gradle is symlinked into the android out dir which is cleaned on `make clean`.
> symlink gradle build dir in out

- Android.mk
Prefix variables in Android.mk with module name to avoid conflicts with other make files in the android source tree.
> prefix variables with module name

- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
Hi, I had some intermittent network issues and noticed my phone would not deep sleep.
I think the McsService does not back off if there is an Exception in the `connect()` method.
The `currentDelay` field is checked, but it is always `0` in that codepath so that a RECONNECT Intent is fired and it loops.
I think it should be enough to use the `getCurrentDelay()` method instead of accessing the field directly.
Here some logs:
````
10-23 16:24:51.769 21174 23719 W GmsGcmMcsSvc: Exception while connecting!
10-23 16:24:51.769 21174 23719 D GmsGcmMcsSvc: Teardown initiated, reason: java.net.UnknownHostException: Unable to resolve host "mtalk.google.com": No address associated with hostname
10-23 16:24:51.772 21174 21174 D GmsGcmTrigger: Not connected to GCM but should be, asking the service to …
```
> McsService does not back off on Failure (Untested Patch included)

- play-services-core/src/main/java/org/microg/gms/maps/ContextContainer.java
The other ContextContainer methods that make use of the UserHandle class are already annotated.
> Add TargetApi annotations to ContextContainer to fix lint errors

- play-services-core/src/main/java/org/microg/gms/gcm/McsInputStream.java
- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
This is an attempt at fixing two issues with tear downs because of connectivity issues:
* When a connect failed (e.g. due to bad network connectivity) I got errors because messages were sent to a dead handler thread. This is because tear downs try to shut down the output stream that has not been started yet. I've added a check if the output handler thread is alive in order to avoid this.
* This morning, my log was filled with messages from `McsInputStream` because `read()` on the input stream returned `-1` and it sent tear down messages to the main handler in a busy loop. I don't know why the main handler did not interrupt the input stream when the first tear down occurred. The tear down messages were handled, triggered the first error, scheduled reconnect attempts with the maximum …
> Fixes for connectivity issues

- patches/android_frameworks_base-M.patch
This commit adds a patch for Android Marshmallow including:
1. Signature Spoofing
2. Location Provider Support
Before building a patched Android Marshmallow system, it is required to execute `make update-api` in the root directory.
> Android Marshmallow Patch

- play-services-core/build.gradle
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/java/org/microg/gms/ui/SettingsActivity.java
- play-services-core/src/main/java/org/microg/tools/selfcheck/SystemChecks.java
- play-services-core/src/main/res/values/strings.xml
I wasn't sure where to put the item, so I can move it to `PermissionCheckGroup` if you prefer.
Note that the Android settings don't seem to be updated properly, so you have to restart your device to see the change in the "Battery Optimization" screen. 
Requires https://github.com/microg/android_packages_apps_UnifiedNlp/pull/100. Hope I did everything right with the submodule.
> Added item to disable battery optimizations

- play-services-core/src/main/res/values/strings.xml
I’m currently working on the french translation and just spotted this.
> Fix small typo in strings

- settings.gradle
Remove safe-parcel gradle sub-project. The git submodule was
already removed by 07ff44e3c6906d65805e01c566e748b817fba0fd.
> Complete removal of safe-parcel subproject

- play-services-core/src/main/java/org/microg/gms/maps/GoogleMapImpl.java
Some map apps like uber are crashing when setOnMapLoadedCallback() gets empty callback. So we check it first.
> Check if callback is non null. Fixes #340 #364.

- play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java
This is necessary for youtube music to work correctly. Otherwise, it doesn't get access to the system accounts, and thus refuses to log in.
> Add youtube music to KNOWN_GOOGLE_PACKAGES

- patches/android_frameworks_base-O.patch
This is android_frameworks_base-N.patch rebased to the android-8.0.0_r4
tag.
It also expands the description a little to let the user know why a
legitimate app might request this permission.
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>
> Add patch for Android O (8.0.0_r4)

- Android.mk
Due to android build tools update, apk is now located inside the "release" subfolder. Build with android.mk was broken.
> Change the location of GmsCore apk

- play-services-core/src/main/java/org/microg/gms/people/PeopleManager.java
This moves the regex parsing of the URL from `loadUserInfo` to `getOwnerAvaterFile`.  This should change the path in the database but leave the file location the same.  This also removes a bit of redundancy in parsing the URL.
This was tested on Google Voice and Hangouts and the avatar now display in the apps.  I'm not sure why the full URL was not being stored in the database, so this may cause a regression if this was intentional.
This should fix #598 and fix #444.
> Fix how avatar URL is saved, fixes #598

- play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java
Tested on Marshmallow 6.0.1 with the latest Google Contacts 3.0.7.210756853. The app no longer crashes on startup. As always, further testing is welcome.
Fixes #589 and fixes #606.
> Add Contacts signature to known google signatures

- play-services-core/src/main/java/org/microg/gms/snet/SafetyNetPrefs.java
- play-services-core/src/main/java/org/microg/gms/ui/SettingsActivity.java
- play-services-core/src/main/res/values-de/strings.xml
- play-services-core/src/main/res/values/strings.xml
After enabling SafetyNet, and if it was never enabled before, set the default Server value to `official`.
Current code leaves it ambigously unset, which is unexpected by the user.
Fixes issue #405 reported by @ale5000-git
> Fix SafetyNet default value

- play-services-core/build.gradle
- play-services-core/src/main/java/com/google/android/gms/common/security/ProviderInstallerImpl.java
This is an implementation of the method `ProviderInstallerImpl` to help protect against SSL exploits.  A new dependency on conscrypt was added and it should be updated periodically.  Minimal testing was done on an unofficial build of CM13, but further testing is welcome.
Fixes #504 and fixes #72.
I tested Hangouts it no longer appears to crash on startup, even without the workaround https://github.com/microg/android_packages_apps_GmsCore/issues/72#issuecomment-303714674.
Issue #86 calls this code so it should probably be tested.  I have not tested Gmail Sync, but I suspect this only fixes one of multiple problems with it.
Other Google and non-Google apps may be affected as well if they attempted to [update the security provider](https://developer.android.com/training/articles/security-gms- …
> Add implementation of ProviderInstallerImpl

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/java/org/microg/gms/gcm/UnregisterReceiver.java
- play-services-core/src/main/java/org/microg/gms/ui/GcmAppFragment.java
A crash occurs if the GCM settings of an app are viewed, the app is uninstalled, and then the settings are viewed again.
This can be replicated as follows:
* Install an app that uses GCM.
* Launch it once so it registers.
* Check app registration status in microG and also tap on it to open the settings page.
* Uninstall the app.
* Go back to microG, which should still be on the settings page for the uninstalled app.
* MicroG instantly crashes.
The crash would occur since the app no longer exists in the database, but the `updateAppDetails` method assumes it does and does not have a null check.
This PR will finish the `Activity` of the `GcmAppFragment` without updating the details if the app was uninstalled while microG was in the background.
In addition, this PR will fix unregistering an …
> Fix app unregistration in Android 8.0+ and prevent a crash

- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
This fixes a NullPointerException when receiving a notification in react-native apps, like Mattermost (https://github.com/mattermost/mattermost-mobile)
The used framework expects the message ID to be present in the app message intent, leading to a NullPointerException when it isn't:
Here is the check: https://github.com/wix/react-native-notifications/blob/master/android/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L66
This returns null: https://github.com/wix/react-native-notifications/blob/master/android/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L47
And finally, the NPE: https://github.com/wix/react-native-notifications/blob/master/android/src/main/java/com/wix/reactnativenotifications/gcm/FcmInstanceId …
> Include GCM message ID in app message intent

- play-services-core/build.gradle
Currently the most recent tag is taken into account when calculating gitVersionBase. While this works as advertised for upstream, which only has v[0-9]* release-tags, this may cause issues on forks (which may have other tags aswell).
This change in build.gradle should make the build system happy in both upstream and fork repos, by switching from `git describe --tags --abbrev=0` to `git tag --list 'v[0-9]*' --sort=-v:refname`.
> build.gradle improve gitVersionBase calculation

- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
This will minimize the number of times certain expensive reflection calls are used by moving them from `handleAppMessage()` to `onCreate()`.
Based on the request by @ale5000-git https://github.com/microg/android_packages_apps_GmsCore/pull/732#issuecomment-485265795
> Optimize some usage of reflection

- play-services-core/src/main/java/org/microg/gms/location/GoogleLocationManagerServiceImpl.java
This method gets a list of location methods an app wants to use, displays a dialog to the user whether to enable them and returns the result to the app, in theory.
The current implementation always returns "network location and GPS enabled, Bluetooth disabled", shows no dialog and returns CANCELLED.
This tips up some apps (eg. `com.tier.app` and  `com.runtastic.android`) and prevents them from accessing the location (also, they show no indication of an error which is not exactly great UX).
This small patch changes the result to SUCCESS which makes the Tier app work at least. (I didn't try Runtastic with this patch.)
A more thorough solution would require comparing the requested values and our fixed values and returning SUCCESS if they match (/ contain each other / overlap?), and …
> Make requestLocationSettingsDialog return success

- play-services-core/src/main/java/com/google/android/gms/common/security/ProviderInstallerImpl.java
The addition of the ProviderInstallerImpl broke com.bankid.bus
(BankID säkerhetsapp). This app is essential to Swedish users since it
is effectively the de facto Swedish online id.
This issue is resolved by adding the app id to the existing black list.
Fixes #824
> Exclude com.bankid.bus from provider installer

- play-services-core/src/main/java/org/microg/gms/gcm/GcmPrefs.java
When using GCM on a roaming connection, the heartbeat interval is set
to: `networkRoaming  * 6000`. It should instead be
`networkRoaming * 60000` because we're converting from a number of
minutes (stored in the properties) to a number of milliseconds, like
it's done for regular mobile and wifi connections.
> Fix GCM heartbeat interval for roaming connections with manual interval

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureNotificationServiceImpl.kt
Hi, `stream.read(byte[] buffer)` does not make an effort to read exactly `buffer.size` bytes, it just tries to read at least 1 byte, and may return with a smaller number of bytes read:
https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipInputStream.html#read(byte[],%20int,%20int)
This was a bug also present in original Google implementation, which resulted in header validation error on some devices.
> Exposure notifications - reading from the stream in a loop

- play-services-base-core/src/main/java/org/microg/gms/common/PackageUtils.java
Adding Google Pay India version signature to known apps.
Relevant Logs:
```
06-25 00:32:21.215  8788  8806 D GmsServicesProvider: query caller=com.google.android.apps.nbu.paisa.user name=primes:shutdown_primes value=null
06-25 00:32:21.243  8788  8788 D GmsClearcutSvc: onBind: Intent { act=com.google.android.gms.clearcut.service.START pkg=com.google.android.gms }
06-25 00:32:21.295  8788  9116 D GmsAuthProvider: Call from com.google.android.apps.nbu.paisa.user
06-25 00:32:21.298  8788  9116 W GmsAuthProvider: Not granting extended access to [com.google.android.apps.nbu.paisa.user], signature: 80df78bb700f9172bc671779b017ddefefcbf552
06-25 00:32:21.299  8788  9116 E DatabaseUtils: Writing exception to parcel
06-25 00:32:21.299  8788  9116 E DatabaseUtils: java.lang.SecurityException: …
```
> Allow Google Pay India

- play-services-core/src/main/java/org/microg/gms/checkin/CheckinClient.java
Actually instantiate objects so that we don't pass `null`. Fixes #1120.
> Fix for #1120

- play-services-core/src/main/AndroidManifest.xml
This PR allows apps to use and register to FCM without having to add `com.google.android.c2dm.permission.RECEIVE` permission in their manifest.
That's because this permission is not required anymore by FCM (see this [official migration guide from GCM to FCM, minute 3:15](https://youtu.be/IeexEiFprY8?t=196)) and causes apps that don't use it to crash (e.g. Google Earth amongst others).
This should fix #1113, fix #939, fix #918 and fix #866.
Note: I haven't tested this PR on a device due to a lack of time. I've just checked that the code builds successfully.
> Don't require apps to use com.google.android.c2dm.permission.RECEIVE permission for GCM/FCM

- play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
'setLocationSource' may be called with a null parameter:
E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter locationSource
E AndroidRuntime: at org.microg.gms.maps.mapbox.GoogleMapImpl.setLocationSource(Unknown Source:2)
> Mapbox: Fix crash when destroying maps

- play-services-basement/src/main/java/com/google/android/gms/common/api/Status.java
- play-services-nearby/src/main/java/org/microg/gms/nearby/ExposureNotificationClientImpl.java
While integrating some microG UI modules bundled with an app, I ran into a situation where sometimes (possibly due to particular sequences of intents/activities), there were various instances of `Status.SUCCESS` around, resulting in failed calls even though they were successful.
This adds a proper `equals()` to remove this possibility.
> Add equals() and hashCode() to Status

- play-services-core/src/main/res/values-ru/plurals.xml
- play-services-core/src/main/res/values-ru/strings.xml
- play-services-nearby-core-ui/src/main/res/values-ru/strings.xml
- play-services-nearby-core/src/main/res/values-ru/strings.xml
- Translate some string as **Cloud Messaging** and **Exposure Notifications** without using brand names and same way it translated by Google to make it easier to understand and find information on the Internet.
https://firebase.google.com/docs/cloud-messaging?hl=ru
https://support.google.com/android/announcements/9929436?hl=ru
- A couple of minor improvement
> Improve Russian translation

- play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/DotChartView.kt
This fixes #1383 by not drawing the legend if the highest datapoint has a value of less than zero. It looks like this then:
> Hide legend if no data is to be displayed

- play-services-base/src/main/java/com/google/android/gms/common/GoogleApiAvailability.java
The class `GoogleApiAvailability` does not have the method [`isGooglePlayServicesAvailable(Context, int)`][1], it only has `isGooglePlayServicesAvailable(Context)`. [CWA tries to access][0] this method, so I think it would be best to provide it here.
[0]: https://github.com/corona-warn-app/cwa-app-android/blob/4431ce3d767b4181281a84cd16639edafc03c07f/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/gplay/GoogleApiVersion.kt#L18
[1]: https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability#isGooglePlayServicesAvailable(android.content.Context,%20int)
> Add missing method to GoogleApiAvailability

- play-services-core/src/main/AndroidManifest.xml
- play-services-nearby-core-ui/src/main/res/navigation/nav_nearby.xml
CCTG could use this when interacting with external microG. Instead of
directly embedding the fragment through the bottomNavigationBar[1] we can
at least jump to the correct target location. Doing this through an
implicit deeplink intent seems easiest as an explicit intent adds all
the top level nav elements to the backstack
(see: https://developer.android.com/guide/navigation/navigation-deep-link).
Tested and this works pretty nicely :).
[1]
> add deeplink to rpi information screen

- play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/DotChartView.kt
Addresses #1441. 
The issue detailed in https://github.com/microg/GmsCore/issues/1441#issuecomment-817174607 is fixed in this PR because it replaces `'m'` with `'M'`.
However I'm not sure under which circumstances the operating system actually provides a `DATE_FORMAT` value. In the emulator nothing was provided. I also think that this string does not provide a great format because it always separates the digits with `/`, which is rather American and not fitting German, for example, where usually `.` is used.
> Fix date format being used incorrectly

- play-services-base-core/src/main/java/org/microg/gms/common/PackageUtils.java
Currently, it crashes on startup. After it's whitelisted, everything seems to work.
> Add Chat to known Google packages

- play-services-core/src/main/AndroidManifest.xml
This small change prevents Google apps from crashing due to an ActivityNotFoundException when the user clicks on "Manage Google account" button. The corresponding intent is now handled by AccountSettingsActivity (currently used as a placeholder for account settings).
> Handle GMS intent for launching account settings

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/AdvertiserService.kt
As discussed, we shouldn't log current RPIs to the system log. In case they are needed, they can still be accessed through the user interface.
> Omit RPIs in log

- play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/ExposureNotificationsRpisFragment.kt
Mainly for CCTG – with this change, we can allow the layout to draw under the translucent system status bar and it will behave exactly as expected:
* Scrollbar does not go through status bar
* Scrolling up scrolls content fully out of the area of the status bar
* Scrolling down scrolls content through the status bar:
Before | After
---|---
There is no change in the microG settings app.
CCTG PR: https://codeberg.org/corona-contact-tracing-germany/cwa-android/pulls/126
> Correctly draw RPIs fragment under system status bar

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureNotificationServiceImpl.kt
This PR removes an outdated log message that was left by mistake after commit aee45c2.
> Remove an outdated and misleading log message

- play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/ExposureNotificationsConfirmActivity.kt
An attempted fix for #1519, inspired by the fix for https://github.com/home-assistant/android/issues/1039
It is not ideal as it requires a double operation by the user: first granting the foreground location, then the background :-/
Tested on LineageOS 17.1, LineageOS 18.1 and stock Android 11 (Samsung A40).
> EN: Fix permission granting on Android 11

- play-services-core/src/main/kotlin/org/microg/gms/ui/DeviceRegistrationFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/DeviceRegistrationPreferencesFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/PushNotificationAdvancedFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/PushNotificationAllAppsFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/PushNotificationAppFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/PushNotificationFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/SafetyNetFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/SettingsFragment.kt
- play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/ExposureNotificationsAppFragment.kt
- play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/ExposureNotificationsFragment.kt
- play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/ExposureNotificationsPreferencesFragment.kt
- play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/ExposureNotificationsRpisFragment.kt
Work around rare crashes that can happen when fragments are not attached to a context while co-routines are still executing but requiring a context.
Change-Id: Ie6c7cee50014b59c25384d3bf9a122081b9917fc
> Work around requireContext() crashes

- Android.mk
The apk path is hardcoded, but it is in fact placed inside the build
path. This patch changes it, so the apk path is calculated from the
build path.
This patch does not change any behavior. However, it allows future
changes to build path to automaticly reflect on the apk path.
> do not hardcode the apk path

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureNotificationServiceImpl.kt
From: https://github.com/corona-warn-app/cwa-documentation/issues/740#issuecomment-963223074
Tested and working via CCTG-TEST:
```
11-09 15:23:45.154 32640 32746 W ExposureNotification: provideDiagnosisKeys() with de.corona.tracing.test/TYZWQ32170AXEUVCDW7A
11-09 15:23:45.182 32640 32713 D ExposureNotification: Using key file supplier
11-09 15:23:45.320 32640 32713 D ExposureNotification: de.corona.tracing.test/TYZWQ32170AXEUVCDW7A processed 592715 keys (1 files pending) in 0.137s -> 2147483.647 keys/s
11-09 15:23:45.331 32640 32713 D ExposureNotification: Verifying signature 1/1
11-09 15:23:45.331 32640 32713 D ExposureNotification: Signature info: algo=1.2.840.10045.4.3.2 key={id=262, version=v1}
11-09 15:23:45.336 32640 32713 I ExposureNotification: Key file verification successful …
```
> add CWA and CCTG exposure file public signing keys

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/AdvertiserService.kt
I have noticed that, while there is support for advertising with version 1.1 of the protocol to also advertise the confidence value of the device, this is not used as the version is fixed to 1.0
> Use ENF version 1.1 to send confidence values

- play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ExposureDatabase.kt
Correctly discard new measurements when the reported timestamp is older
than the timestamp in the database.
Fixes https://github.com/microg/GmsCore/issues/1655.
> ENF: Fix average RSSI calculation

- play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
Kotlin's `..` operator includes the upper bound contrary to `until`. Including the `size()` value of `LongSparseArray` produces an `ArrayIndexOutOfBoundsException`. This reproduces in the current (5.0.41 (550)) version of the Tisséo (fr.tisseo.android) application. Here is the stacktrace:
```
06-01 14:01:00.961 E/AndroidRuntime(24926): FATAL EXCEPTION: main
06-01 14:01:00.961 E/AndroidRuntime(24926): Process: fr.tisseo.android, PID: 24926
06-01 14:01:00.961 E/AndroidRuntime(24926): java.lang.ArrayIndexOutOfBoundsException: length=126; index=126
06-01 14:01:00.961 E/AndroidRuntime(24926): 	at androidx.collection.LongSparseArray.valueAt(LongSparseArray.java:377)
06-01 14:01:00.961 E/AndroidRuntime(24926): 	at org.microg.gms.maps.mapbox.GoogleMapKt.values(GoogleMap.kt:61)
06-01 14:01:00.961 …
```
> Prevent an ArrayIndexOutOfBoundsException when calling extension function LongSparseArray.values() in GoogleMap.kt

- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
According to Google Firebase's doc, other ports than 5228 can be used:
If your organization has a firewall to restrict traffic to or from
the Internet, you need to configure it to allow mobile devices to
connect with FCM in order for devices on your network to receive
messages. FCM typically uses port 5228, but it sometimes uses 443,
5229, and 5230.
Src: https://firebase.google.com/docs/cloud-messaging/concept-options#messaging-ports-and-your-firewall
As suggested by @mar-v-in, it is enough to first try 5228 and then only
try with 443 as fall back port. Indeed, it would be surprising to find
any firewall blocking port 5228 but not 5229.
Closes: https://github.com/microg/GmsCore/issues/408
Note: this PR was marked as "Draft" for the moment for 2 reasons:
- I didn't code in Java for years …
> MCS: fallback to port 443 if 5228 is blocked

- play-services-fido-api/src/main/java/com/google/android/gms/fido/fido2/api/common/BrowserPublicKeyCredentialCreationOptions.java
It was meant[1] to be
setPublicKeyCredentialCreationOptions,
not
setPublicKeyCredentialRequestOptions.
[1] https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/api/common/BrowserPublicKeyCredentialCreationOptions.Builder#public-method-summary
> Fido: Fix BPKCCO.Builder method

- play-services-fido-api/src/main/java/com/google/android/gms/fido/fido2/api/common/FidoAppIdExtension.java
FidoAppIdExtension class should have a constructor[1] with the appId argument.
[1] https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/api/common/FidoAppIdExtension#public-constructors
> Fido: implement FidoAppIdExtension constructor

- play-services-core/src/main/java/org/microg/gms/firebase/dynamiclinks/DynamicLinksServiceImpl.java
Avoid sending empty initial links to apps, use null like stock GMS. Empty links can confuse apps such as Jitsi Meet when the proper link has already been delivered as an intent.
> use null initial dynamic link

- play-services-base-core/src/main/java/org/microg/gms/common/PackageUtils.java
- play-services-basement/src/main/java/org/microg/gms/common/Constants.java
Recently a lot of versions of Google Play Services and Google Play Store include two signatures.
I don't think we need to change something yet in the signature spoofing but we can at least prepare the code to accept it.
You can see it here:
- https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-22-30-17-release/
- https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-32-3-14-release/
> Add the secondary Google package signature

- gradle.properties
Fixes build issue with JVM OOM, when user's build environment is not already setting these values to an increased memory amount in `~/.gradle/gradle.properties`
> Increase build memory

- play-services-basement/src/main/java/com/google/android/gms/dynamic/ObjectWrapper.java
Using GmsCore and JaCoCo with an instrumented test app built with Android Gradle Plugin version > 7.1.2 causes:
```
java.lang.Exception: java.lang.IllegalArgumentException
..at com.google.android.gms.dynamic.ObjectWrapper.unwrap(ObjectWrapper.java:43)
```
> Fix IllegalArgumentException with JaCoCo + AGP >= 7.3.0

- play-services-fido-core/src/main/kotlin/org/microg/gms/fido/core/transport/TransportHandler.kt
Fixes #1806
I have verified this patch using a NFC token, see the issue for details. Regression testing was performed against a Yubikey 5 NFC.
> FIDO: Handle test-of-user-presence-required in ctap1DeviceHasCredential

- play-services-fido-core/src/main/kotlin/org/microg/gms/fido/core/transport/nfc/CtapNfcConnection.kt
This PR increases the timeout for raw NFC transceive operations in the CTAP transport to 5 seconds.
This is needed because my phone (Galaxy S7) and my FIDO2 tag (NXP P71) are somewhat slow in terms of communication and computation (e.g. key generation). I assume many other users might run into these limitations. Without this increased timeout, the tag will be assumed lost while the applet is still computing `authenticatorMakeCredential`:
```
2022-10-25 11:26:14.457 32731-1529/com.google.android.gms D/FidoCtapNfcConnection: Selecting AID: oAAABkcvAAE=
2022-10-25 11:26:14.520 32731-1529/com.google.android.gms D/FidoCtapNfcConnection: Device sent version: FIDO_2_0
2022-10-25 11:26:14.522 32731-1529/com.google.android.gms D/FidoCtapNfcConnection: Send CTAP2 command: gBAAAAAAAQQ=
2022-10-25 …
```
> FIDO: Increase IsoDep timeout for NFC CTAP connection

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/res/xml/preferences_auth.xml
Turns out that those intents may resolve to activities from Vanced microG, resulting a UID mismatch between resolved app (Vanced) and authenticator app (microG).
Validated by uninstalling Vanced microG, after which the AccountSettingsActivity launched as expected.
This is an attempt to eliminate the conflict.
Logcat from Settings app:
```
AccountTypePrefLoader: Refusing to launch authenticator intent becauseit exploits Settings permissions: Intent { act=com.google.android.gms.accountsettings.PRIVACY_SETTINGS flg=0x10000000 (has extras) }
```
Reference: https://cs.android.com/android/platform/superproject/+/master:packages/apps/Settings/src/com/android/settings/accounts/AccountTypePreferenceLoader.java;l=166;drc=6d97d6d7215fef247d1a90e05545cac3676f9212?q=Refusing%20to%20launch%20authenticat …
> Specify targetPackage for intents from Authenticator Preferences

- play-services-maps-core-mapbox/build.gradle
- play-services-maps-core-mapbox/src/main/AndroidManifest.xml
This fixes #969 but requires setting the minimum Android version to 5.0. It may need more testing since breaking changes may be present in org.maplibre.gl:android-sdk.
> Update mapbox libraries

- play-services-core/build.gradle
- play-services-core/src/main/kotlin/org/microg/gms/provision/ProvisionService.kt
New provisioning extras to control Location features:
* Internet lookups (Mozilla Location Services): wifi_mls, cell_mls
* Local location learning: wifi_learning, cell_learning
* Query location from supported hotspots: wifi_moving
* Geocoder (Nominatim): nominatim_enabled
> Provisioning: Location providers

- play-services-core/src/main/kotlin/org/microg/gms/gcm/GcmPrefs.kt
The previous maximum of 30 minutes is too high for a worst case, potentially resulting in massive notification delays on any network but especially on certain less-reliable networks.
> Set max auto heartbeat interval to 15min

- play-services-core/multidex-keep.pro
@mar-v-in
It doesn't fix all the problems in the logcat but it at least allow to reach the phase of:
`D/GmsProviderInstaller( 1270): Installed default security provider GmsCore_OpenSSL`
and so the sync adapter can sync correctly.
> Keep Conscrypt and Dynamite Loader in the primary dex file otherwise it will error out on legacy Android versions, fix #2023

- play-services-core/src/main/kotlin/org/microg/gms/games/GamesService.kt
Fixes a warning I noticed when launching Clash Royale. It worked regardless, but it might help in other games.
> Add a missing null check in GamesService

- play-services-base/core/src/main/kotlin/org/microg/gms/profile/ProfileManager.kt
Indeed, we used to face a FileAlreadyExistsException when importing a user profile again.
> Allow the imported user profile to be overwritten

- play-services-base/core/src/main/kotlin/org/microg/gms/profile/ProfileManager.kt
User profile was not read at the time the SafetyNet request is done because getProfileResId() was returning 0 in that case.
We need to check profile resources id only when user profile is not selected.
> Fix user profile behavior

- play-services-location/core/provider/src/main/kotlin/org/microg/gms/location/network/wifi/MovingWifiHelper.kt
Self-explanatory. Tested with _SNCF_WIFI_INOUI.
Edit: There may be a second endpoint specifically used on Intercités night trains at [www.ombord.info/api/jsonp/position/](www.ombord.info/api/jsonp/position/) using the same SSID as daytime Intercités, though I am unable to verify that.
> Location: add SNCF/Ouigo location lookup support

- play-services-maps/core/mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/Styles.kt
If the `json` String of the `MapStyleOptions` is empty, then the result of `Gson().fromJson(json, ...)` will be null which currently leads to an unhandled NullPointerException as soon as `styleOperations` is accessed causing an application crash:
```
java.lang.NullPointerException: styleOperations must not be null
at org.microg.gms.maps.mapbox.StylesKt.apply(Styles.kt:119)
at org.microg.gms.maps.mapbox.StylesKt.getStyle(Styles.kt:79)
at org.microg.gms.maps.mapbox.StylesKt.getStyle$default(Styles.kt:42)
at org.microg.gms.maps.mapbox.GoogleMapImpl.applyMapStyle(GoogleMap.kt:385)
at org.microg.gms.maps.mapbox.GoogleMapImpl.setMapType(GoogleMap.kt:371)
```
The crash doesn't occur on phones that use Google Play Services; therefore, the null check fixes the crash and aligns the API with the …
> fixes unhandled NullPointerException for styleOperations

- play-services-droidguard/core/src/main/kotlin/org/microg/gms/droidguard/core/HandleProxyFactory.kt
fixes an exception <process unstable thread limit> Caused by Repeated Thread Creation.
> fixes an exception <process unstable thread limit>

- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/MainActivity.kt
The Google Maps Timeline function cannot be used properly because the domain name has changed.
> Added new domain name to Google Maps Timeline

- fake-signature/src/huawei/java/com/huawei/signature/diff/SignatureService.java
Binder.getCallingUid() should be used for permission judgment.
> fixed the bug in the signature spoofing module

- play-services-base/core/src/main/res/layout/preference_switch_bar.xml
- play-services-core/build.gradle
- play-services-core/microg-ui-tools/src/main/java/org/microg/tools/ui/AbstractSettingsActivity.java
- play-services-core/microg-ui-tools/src/main/res/layout/settings_activity.xml
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/java/org/microg/gms/ui/MainSettingsActivity.java
- play-services-core/src/main/res/color/preference_material_switch_color.xml
- play-services-core/src/main/res/layout/preference_material_switch.xml
- play-services-core/src/main/res/layout/settings_root_activity.xml
- play-services-core/src/main/res/values-night-v23/themes.xml
- play-services-core/src/main/res/values-night-v27/themes.xml
- play-services-core/src/main/res/values-night-v31/themes.xml
- play-services-core/src/main/res/values-v23/themes.xml
- play-services-core/src/main/res/values-v27/themes.xml
- play-services-core/src/main/res/values-v31/themes.xml
- play-services-core/src/main/res/values/themes.xml
This PR:
- Sets status and navigation bar color as per different API levels,
- Switches to M3 theme on and above Android 12.0 devices,
- Moves to `Toolbar` instead of action bar theme which works better with theming
> play-services-core: Theme improvements

- play-services-api/build.gradle
- play-services-api/src/main/aidl/com/google/android/gms/audit/LogAuditRecordsRequest.aidl
- play-services-api/src/main/aidl/com/google/android/gms/audit/internal/IAuditService.aidl
- play-services-api/src/main/java/com/google/android/gms/audit/LogAuditRecordsRequest.java
- play-services-basement/src/main/java/com/google/android/gms/common/api/Status.java
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/com/google/android/gms/audit/internal/AuditApiService.kt
Solve the problem that Google_Authenticator cannot log in using Google (complete the AuditApiService implementation numbered 154 in GmsService)
> Add dummy service for AUDIT(154)

- vending-app/build.gradle
- vending-app/src/main/AndroidManifest.xml
- vending-app/src/main/java/com/android/vending/Util.java
- vending-app/src/main/java/com/android/vending/licensing/LicenseChecker.java
- vending-app/src/main/java/com/android/vending/licensing/LicenseRequest.java
- vending-app/src/main/java/com/android/vending/licensing/LicenseServiceNotificationRunnable.java
- vending-app/src/main/java/com/android/vending/licensing/LicensingService.java
- vending-app/src/main/proto/LicenseRequest.proto
- vending-app/src/main/proto/LicenseResult.proto
- vending-app/src/main/proto/Locality.proto
- vending-app/src/main/proto/Timestamp.proto
- vending-app/src/main/res/drawable/ic_notification.xml
- vending-app/src/main/res/values/strings.xml
Implemented as of now:
* Licensing requests
* Query multiple Google accounts
* If no Google account is registered, show a notification
* Query profile service
* Query preference for whether licensing is enabled
> Implement Licensing service

- play-services-location/core/src/main/kotlin/org/microg/gms/location/manager/LocationRequestManager.kt
…it is opened for the first time.
> Location: handle invalid or dead old binder on location request update

- .github/workflows/build.yml
I have done some changes:
- Added "workflow_dispatch", this will allow you to run the build manually if needed in addition of the automatic run;
- Remove all permissions from the actions since they aren't needed for a simple build;
- Update the versions of actions (older versions will probably break soon);
- Start using the official action to setup Gradle since it handle caching automatically in a better way compared to setup java action (the first run will be slower due to cache changes but the following runs will decrease);
- Remove useless ENV variables, the ram of Gradle is already configured inside gradle.properties and the other is probably a remnant of the past;
- Minor cosmetic improvements.
> Optimize Gradle build on GitHub

- play-services-basement/src/main/java/org/microg/gms/auth/AuthConstants.java
- play-services-core/src/main/java/org/microg/gms/auth/AuthManagerServiceImpl.java
Fixed the login exception issue when the scope is "oauth2:" 
e.g. Chai - Chat with AI Friends
> Fixed the login exception issue when the scope is "oauth2:"

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/res/values/strings.xml
Declare CAR_SPEED permission fix the Google Maps location permission authorization pop-up window when connecting to Android Auto.
I have declared the others as well.
Derived from #2123
> Declare car related permissions

- play-services-maps/core/mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
Taxi G7 app was throwing this exception at startup.
It seems like Taxi G7 callbacks are adding new callbacks to execute.
> Fix ConconcurrentModificationException in Maps

- vending-app/src/main/AndroidManifest.xml
- vending-app/src/main/java/com/google/android/finsky/billing/lightpurchase/LightPurchaseFlowActivity.java
- vending-app/src/main/java/org/microg/vending/billing/LightPurchaseFlowActivity.java
- vending-app/src/main/res/values-zh-rCN/strings.xml
- vending-app/src/main/res/values/strings.xml
Solve the problem of crash caused by some in-app purchases jumping to the LightPurchaseFlowActivity page through action:com.android.vending.billing.PURCHASE.
e.g. Google Play Books
> Vending: Add PurchaseActivity dummy

- .github/matchers/gradle-build-kotlin-error-matcher.json
- .github/matchers/gradle-build-kotlin-error-matcher.json.license
- .github/matchers/gradle-build-matcher.json
- .github/matchers/gradle-build-matcher.json.license
- .github/workflows/build.yml
- Added Gradle Wrapper validation to detect malicious or corrupted Gradle wrappers.
- Added problem matcher to automatically add GitHub annotations for build errors (especially useful for PR).
**Note:** It doesn't add warnings since there are too many.
Screenshot example:
> GitHub Gradle build improvements

- play-services-location/core/src/main/kotlin/org/microg/gms/location/ui/LocationPreferencesFragment.kt
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.google.android.gms/databases/geoapps.db
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:58)
at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1422)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1298)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1504)
at org.microg.gms.location.manager.LocationAppsDatabase.listAppsByAccessTime(LocationAppsDatabase.kt:72)
at org.microg.gms.location.manager.LocationAppsDatabase.listAppsByAccessTime$default(LocationAppsDatabase.kt:70)
at org.microg.gms.location.ui.LocationPreferencesFragment$updateContent$1$1.invokeSuspend(LocationPreferencesFragme …
> Location: Catch exception when accidentally reusing apps database

- play-services-core/src/main/java/org/microg/gms/ui/AccountsFragment.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/SettingsFragment.kt
- play-services-core/src/main/res/navigation/nav_settings.xml
- play-services-core/src/main/res/values/strings.xml
- play-services-core/src/main/res/xml/preferences_accounts.xml
- play-services-core/src/main/res/xml/preferences_start.xml
Add a new fragment to host preferences that concern accounts or data related to them.
* Show currently logged-in accounts as a simple list on the top
* Relocate add account preference below.
* Add a new preference to open account settings page to manage all accounts quickly.
> Introduce a new AccountsFragment to store accounts related prefs

- vending-app/build.gradle
Optimizations are mainly for releases, in debug builds they are less needed; this will reduce the pressure.
> Disable some optimizations on debug builds

- .github/dependabot.yml
When there is an update a pull request is created automatically, so the only manual work needed is the merge button.
It is limited to a single pull request at a time.
Please merge #2341 before this to avoid conflits with the "position" change of the action.
> Add update check for Github actions, it save a lot of manual work

- play-services-basement/src/main/java/org/microg/gms/gcm/GcmConstants.java
- play-services-core/src/main/java/org/microg/gms/gcm/McsService.java
This PR fixes broken notifications on apps that rely on `google.sent_time` such as Telegram.
Fixes #1986
Fixes #2298
> Add google.sent_time extra to C2DM receive intent, fixes Telegram notifications

- play-services-maps/core/mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
With this implementation, a delay is added before calling back an `onMapLoadedCallback`.
Issues:
* As it is just a workaround, it does not guarantee that the map is actually loaded. Thus the snapshot Signal takes can still be empty – however, if the map was zoomed in previously, the tiles are already cached and will be rendered correctly within the 500ms delay. (Unlike a _completely_ empty snapshot, not showing even the MapLibre logo, that was the result before.)
* <del>Sometimes there is a crash in Signal that I still need to investigate where it is coming from.</del> (https://github.com/signalapp/Signal-Android/pull/13461)
Fixes https://github.com/microg/GmsCore/issues/1960. Re. https://github.com/signalapp/Signal-Android/issues/12723#issuecomment-1595810834, see also …
> Workaround implementation for `onMapLoadedCallback`

- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/extensions.kt
The processing has already been done when requesting the authorized content for the first time, so there is no need to request consent here. Otherwise, login will be impossible.
> Auth: Remove unnecessary prompts

- vending-app/src/main/AndroidManifest.xml
- vending-app/src/main/aidl/com/google/android/play/core/assetpacks/protocol/IAssetModuleService.aidl
- vending-app/src/main/aidl/com/google/android/play/core/assetpacks/protocol/IAssetModuleServiceCallback.aidl
- vending-app/src/main/java/com/google/android/finsky/assetmoduleservice/AssetModuleService.java
Supplementary store AssetModuleService service is used to solve the problem that League of Legends: Wild Rift cannot be opened normally.
> Vending: Add AssetModuleService dummy

- play-services-core/microg-ui-tools/src/main/res/values-be/strings.xml
- play-services-core/microg-ui-tools/src/main/res/values-ru/strings.xml
- Respect small displays with big font (Self-check)
- Grammar correction
> Correct RU and BE strings missing on weblate

- README.md
- TRANSLATION.md
microG currently does not advertise its Weblate instance anywhere. Because of this, most people don't know that microG has one. The only way to tell is by checking commits and checking the import translation commits. 
This PR attempts at addressing that by giving documentation on how translations work and pointing to it in README.
* Creates a TRANSLATION.md file meant to explain the state of translations for the microG project
* Adds a widget that shows how translated out of the supported languages microG is
* Adds a section that points to TRANSLATION.md in the README
* Inside README, the lack of microG-UI-tools in Weblate is pointed out so that translators are aware of this issue and can translate it without realizing it only after a release happens
Fixes #2303
> Better discovery on how to translate microG

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
GroundOverlayOptions width , height, bounds， If the requirements are not met, the app will crash.
eg:gojek
> Improved map addGroundOverlay method

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
before fixing:
After modification:
> fix whatsapp map is blurry

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
It was found that some applications cannot display map content because they are set to use satellite maps, but the SDK does not support them.
> Map: Remove styles that cannot be set

- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/MainActivity.kt
Google App - Settings - Privacy and Security Clicking Ads Personalization does not work
> Add Google Ads Personalization settings

- play-services-api/src/main/java/com/google/android/gms/credential/manager/invocationparams/CallerInfo.java
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/com/google/android/gms/credential/manager/PasswordManagerActivity.kt
- play-services-core/src/main/kotlin/org/microg/gms/credential/CredentialManagerService.kt
During the testing of the latest version of Google Chrome, clicking the password management tool in the settings did not respond. The CREDENTIAL_MANAGER service method needs to be improved. 
e.g. Google Chrome <126.0.6478.110>
> Supplement Google Password Manager functionality

- vending-app/src/main/java/com/google/android/finsky/assetmoduleservice/AssetModuleService.java
Some applications are unable to enter the home page due to repeated requests.
e.g. Among Us
> Vending: Improve AssetModuleService

- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/AssistedSignInActivity.kt
- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/AssistedSignInFragment.kt
Fixed the issue that caused quick login to crash due to UNREGISTERED_ON_API_CONSOLE.
e.g. DeutschlandCard (de.deutschlandcard.app)
> Fixed the issue that caused quick login to crash 

- play-services-base/src/main/java/com/google/android/gms/auth/api/signin/GoogleSignInOptions.java
- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/AuthSignInService.kt
- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/SignInConfigurationService.kt
- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/extensions.kt
Fixed the issue that authToken was not reset when logging out, which caused the next login failure.
The reason was that the options when logging in were inconsistent with the options when logging out.
e.g. Subway Surfers<com.kiloo.subwaysurf>
> Improve the signOut method of AuthSignInService

- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingCreateAlternativeBillingOnlyTokenCallback.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingCreateExternalPaymentReportingDetailsCallback.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingDelegateToBackendCallback.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingGetAlternativeBillingOnlyDialogIntentCallback.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingGetBillingConfigCallback.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingGetExternalPaymentDialogIntentCallback.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingIsAlternativeBillingOnlyAvailableCallback.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingIsExternalPaymentAvailableCallback.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl
- vending-app/src/main/aidl/com/android/vending/billing/IInAppBillingServiceCallback.aidl
- vending-app/src/main/java/org/microg/vending/billing/InAppBillingServiceImpl.kt
- vending-app/src/main/java/org/microg/vending/billing/core/HttpClient.kt
Improved the IAP interface and fixed some payment issues, such as: Strava: Run, Bike, Hike, SoundCloud: Play Music & Songs
> Improve the IAP interface

- play-services-fido/core/src/main/kotlin/org/microg/gms/fido/core/transport/screenlock/ScreenLockCredentialStore.kt
When registering a FIDO2 key using the ScreenLockCredentialStore, the process currently throws an exception if the Android Keystore does not have a default attestation key to sign the newly generated key pair with (as is the case for both phones I've tested on). I've added code to catch this exception and try generating a key pair again without any attestation. Also added code to use Strongbox if available, although this hasn't been tested since none of my phones have Strongbox.
Also added code that allows signing in with screenlock even if the requesting party has not supplied an allowed credential list. Currently, the code looks through the keystore for all keys that match the requesting party ID, and returns the first one it finds. In the future, the user should probably be allowed to …
> FIDO2 screenlock authentication fixes

- play-services-location/core/provider/src/main/kotlin/org/microg/gms/location/network/wifi/MovingWifiHelper.kt
The new JSON dosen't include a "fix" field on french intercity trains anymore, but they're still in use on TGVs and OUIGO
> MovingWifiHelper: Fix _SNCF_WIFI_INTERCITES

- play-services-maps/core/mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/LiteGoogleMap.kt
Spotify was crashing because of some lateinit property in Spotify snapshot ready callback was not initialized.
Looking at the condition we can observe that GmsCore was calling the snapshot ready callback when the snapshot was null, which does not make sense.
Inverting the logic and calling the callback when the snapshot was not null anymore fixed the issue and Spotify was able to display the snapshot.
> Fix getMapAsync() for LiteGoogleMap

- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/MainActivity.kt
No redirect when clicking on account avatar on Google App account management page
> Account settings: Allow profile picture page

- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/MainActivity.kt
- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/extensions.kt
Fixed the issue in YouTube settings where clicking Manage all history would redirect to Google search history.
Google search history and YouTube Manage all history share the same screenId.
> Account Settings: Take product name into MyActivity page

- play-services-base/src/main/java/org/microg/gms/common/MultiConnectionKeeper.java
- play-services-basement/src/main/java/org/microg/gms/common/Constants.java
- play-services-core/build.gradle
- play-services-core/microg-ui-tools/src/main/java/org/microg/tools/ui/AbstractSelfCheckFragment.java
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/java/org/microg/gms/ui/MainSettingsActivity.java
- play-services-core/src/main/java/org/microg/gms/ui/SelfCheckFragment.java
- play-services-core/src/main/res/values/strings.xml
- play-services-core/src/main/res/xml/preferences_auth.xml
- play-services-core/src/main/res/xml/preferences_start.xml
Following discussion on #2183  (which may be closed ? Superseded by this one)
@mar-v-in @ale5000-git
I have tested, and org.microg.gms can't be installed on a system with com.google.android.gms (Google or microG) because of _duplicate permission_.
I have used the dimension 'target' for the user flavor, I think that's the one to use.
> Add user-install microG User Services

- play-services-core-proto/src/main/proto/help.proto
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/org/microg/gms/googlehelp/ui/GoogleHelpRedirectActivity.kt
The test found that there are two places where you cannot jump to the help page.
1. Gmail meeting menu pop-up window click to learn more Unable to jump.
2. Clicking Learn how to verify your phone number on the Meet add phone number page does not redirect.
> Google Help: Improve the link target

- vending-app/src/main/java/org/microg/vending/billing/InAppBillingServiceImpl.kt
Fixed the issue that the payment pop-up page could not be displayed after clicking on the payment.
e.g. uk.co.nationalrail.google
> IAP: Implement old getBuyIntent through forwarding to new one

- play-services-maps/core/mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/model/InfoWindow.kt
Since views cannot have two parents at the same time, we encounter a crash when a client provides us with a view  to be used as an InfoWindow which already has a parent. The simple solution is to remove the parent.
Fixes  #2558.
> Fix InfoWindow when provided view already has parent

- play-services-core/src/main/res/drawable-v21/ic_app_settings_system.xml
Fix microG settings icon not following system theme, fix https://github.com/microg/GmsCore/issues/2616
> Fix microG settings icon not following system theme

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
When using Uber, I found that the route information that appeared would drift when I moved the map. I am not sure if it is due to the map, so I will not calculate the route to display during the movement.
> HMS Maps: Optimize the phenomenon of Uber route drift.

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
Fix CameraPosition NullPointerException
> HMS Maps: Fix CameraPosition NullPointerException

- play-services-base/core/src/main/kotlin/org/microg/gms/common/KnownGooglePackages.kt
- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/MainActivity.kt
- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/extensions.kt
Fixed the issue that when creating a child account in Family Link, clicking Continue does not respond.
com.google.android.apps.kids.familylink
> Fix issues with Family Link

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java
Fixed the issue that multiple LoginActivity pages exist in the background record when logging in via GoogleTv.
> Fix the exception about LoginActivity

- firebase-dynamic-links/build.gradle
- firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/DynamicLinkData.java
- play-services-appinvite/core/src/main/kotlin/org/microg/gms/appinivite/AppInviteActivity.kt
Fixed AI Chatbot - Nova account registration issue
Package name: com.scaleup.chatai
Reproduction steps:
1. Open the APP, click "Sign up for Free"
2. Enter your email address
3. Open the email APP, click the corresponding link
4. Jump to the corresponding details page of the app market
Normal process:
Click the link in the email to jump to AI Chatbot - Nova and complete the registration
> Add support for DynamicLinkData on app invite links.

- play-services-tapandpay/core/src/main/kotlin/org/microg/gms/tapandpay/TapAndPayService.kt
- play-services-tapandpay/src/main/aidl/com/google/android/gms/tapandpay/internal/ITapAndPayService.aidl
- play-services-tapandpay/src/main/aidl/com/google/android/gms/tapandpay/internal/ITapAndPayServiceCallbacks.aidl
- play-services-tapandpay/src/main/aidl/com/google/android/gms/tapandpay/issuer/TokenInfo.aidl
- play-services-tapandpay/src/main/java/com/google/android/gms/tapandpay/issuer/TokenInfo.java
APP:Pluxee
packagename:com.sodexo.cwc.ro
Screenshot of the problem:
Normal phenomenon: You can see the card information and consumption records
> Add more dummies to TapAndPay service

- play-services-base/core/src/main/kotlin/org/microg/gms/profile/ProfileManager.kt
- vending-app/src/main/java/org/microg/vending/billing/Utils.kt
Reproduction steps:
1.Install vending without installing mg
2.Find an APP to trigger IAP and trigger build info initialization
3.install mg
4.IAP problem found
The problem is that the build info of vending depends on mg. If mg is not installed, the parameters in the build are null. The build info is initialized only once, so it will not be initialized again after mg is installed, resulting in the parameters in the build being null all the time.
> Fix vending build info initialization parameter is null

- vending-app/src/main/java/com/google/android/finsky/externalreferrer/GetInstallReferrerService.java
> Fixed the pop-up window issue on Twitch

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/res/values/permissions.xml
From Android 10 it use `android.permission.ACTIVITY_RECOGNITION` but before 10 it was a gms permission (`com.google.android.gms.permission.ACTIVITY_RECOGNITION`), so declare it for old Apps / old Android versions.
> Add Activity recognition permission

- play-services-ads/core/src/main/java/com/google/android/gms/dynamite/descriptors/com/google/android/gms/ads/dynamite/ModuleDescriptor.java
- play-services-core/src/main/java/com/google/android/gms/chimera/container/DynamiteContext.java
- play-services-core/src/main/java/com/google/android/gms/chimera/container/DynamiteModuleInfo.java
Added a new DynamiteModule initialization method to initialize some necessary content. 
For example, this commit can effectively avoid the ANR problem of the new version of X on some mobile devices.
> DynamiteModule: Added <init> method

- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/AssistedSignInActivity.kt
- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/AssistedSignInFragment.kt
Fixed the issue with the quick login pop-up window on the folding screen.
11-01 16:37:06.109 20931 20931 E AndroidRuntime: Process: com.google.android.gms:ui, PID: 20931
11-01 16:37:06.109 20931 20931 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.auth.signin.AssistedSignInActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.microg.gms.auth.signin.AssistedSignInFragment: could not find Fragment constructor
11-01 16:37:06.109 20931 20931 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4866)
11-01 16:37:06.109 20931 20931 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:5090)
11-01 …
> Auth: Fix exceptions caused by folding screens

- play-services-appset/core/src/main/kotlin/org/microg/gms/appset/AppSetService.kt
When the application connects to the service, using the ID "0000-xxx" will result in no response. 
Changing to a random ID will work properly.
e.g. de.zalando.mobile
> AppSet: Set a default random ID

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/MapFragment.kt
Fixed the issue that the app cannot use the Maps function normally.
e.g. com.weekendhk.jetsonews
> Maps: Added <GoogleMapZoomInButton> Issue fixed

- play-services-location/core/src/main/kotlin/org/microg/gms/location/reporting/ReportingServiceInstance.kt
Fixed the related <Error turning on Location History> pop-up window.
e.g. com.google.android.apps.paidtasks
> Reporting: Google applications are allowed by default

- play-services-auth-api-phone/core/src/main/kotlin/org/microg/gms/auth/phone/SmsRetrieverCore.kt
When using the following application, I found that the text message I received when registering was not displayed completely through the service, and the text message sent by the application exceeded the length.
e.g. com.boynergrup.hopi
> Sms: Improve the problem of incomplete information due to long SMS

- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/MainActivity.kt
Fixed Google Contacts App not responding when clicking on family group.
> Fixed the issue of not being able to jump to the family group page

- play-services-fido/src/main/java/com/google/android/gms/fido/fido2/api/common/EC2Algorithm.java
【Uber】Manage Uber Account-Security-Create Pass Key page and click Create
> Fido: Fix Uber cannot create passkey

- play-services-vision/core/src/main/kotlin/org/microg/gms/vision/barcode/BarcodeDecodeHelper.kt
- play-services-vision/core/src/main/kotlin/org/microg/gms/vision/barcode/BarcodeDetector.kt
- play-services-vision/core/src/main/kotlin/org/microg/gms/vision/barcode/BarcodeScanner.kt
- play-services-vision/core/src/main/kotlin/org/microg/gms/vision/barcode/RawBarcodeData.kt
1.Added new processing for rotation
2.Image recognition support
test app:
1.https://github.com/googlesamples/mlkit
2.ebay homepage search barcode scan
> Barcode Optimization

- firebase-auth/core/src/main/AndroidManifest.xml
- firebase-auth/core/src/main/kotlin/org/microg/gms/firebase/auth/FirebaseAuthService.kt
- firebase-auth/core/src/main/kotlin/org/microg/gms/firebase/auth/ReCaptchaActivity.kt
- firebase-auth/core/src/main/kotlin/org/microg/gms/firebase/auth/ReCaptchaOverlayActivity.kt
- firebase-auth/core/src/main/kotlin/org/microg/gms/firebase/auth/ReCaptchaOverlayService.kt
- firebase-auth/core/src/main/kotlin/org/microg/gms/firebase/auth/extensions.kt
- vending-app/src/main/AndroidManifest.xml
12-13 15:35:42.347  4474  4474 E AndroidRuntime: FATAL EXCEPTION: main
12-13 15:35:42.347  4474  4474 E AndroidRuntime: Process: com.google.android.gms:ui, PID: 4474
12-13 15:35:42.347  4474  4474 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.auth.login.LoginActivity}: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.google.android.gms:ui (pid 4474), lock owner com.google.android.gms (pid 5405)
12-13 15:35:42.347  4474  4474 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4841)
12-13 15:35:42.347  4474  4474 E AndroidRuntime: 	at …
> Webview: Fix the exception after multi-process access

- vending-app/src/main/AndroidManifest.xml
- vending-app/src/main/aidl/com/google/android/finsky/services/IPlayGearheadService.aidl
- vending-app/src/main/kotlin/com/google/android/finsky/services/PlayGearheadService.kt
Fixed Yandex Map/Navigator not being displayed via AndroidAuto.
> Vending: Add PlayGearheadService dummy

- vending-app/src/main/java/org/microg/vending/billing/InAppBillingServiceImpl.kt
In the case of multiple accounts, when switching accounts to pay, there is a situation where the payment is made using the information of the previous account.
> IAP: Fix the exception in multiple account situations

- play-services-location/core/provider/src/main/kotlin/org/microg/gms/location/network/wifi/MovingWifiHelper.kt
This is an untested implementation of moving WiFi locations for Eurostar (see https://github.com/microg/GmsCore/issues/2769).
Feedback and/or testers would be welcome.
> Location: Support moving WiFi location for Eurostar trains

- play-services-core/src/main/java/org/microg/gms/people/PeopleManager.java
- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/MainActivity.kt
- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/WebViewHelper.kt
- play-services-core/src/main/kotlin/org/microg/gms/accountsettings/ui/extensions.kt
- play-services-core/src/main/kotlin/org/microg/gms/ui/AccountsFragment.kt
1. Fixed the issue that some pages corresponding to screenId cannot interact normally after clicking on the content.
e.g. Maps -> Your Profile -> Edit Profile
2. The local avatar is not changed after modifying the avatar.
> MainActivity: Add Javascript interactive content

- play-services-core/src/main/AndroidManifest.xml
- play-services-fitness/core/src/main/AndroidManifest.xml
- play-services-fitness/core/src/main/kotlin/com/google/android/gms/fitness/service/config/FitConfigBroker.kt
- play-services-fitness/core/src/main/kotlin/com/google/android/gms/fitness/service/extensions.kt
- play-services-fitness/core/src/main/kotlin/com/google/android/gms/fitness/service/history/FitHistoryBroker.kt
- play-services-fitness/core/src/main/kotlin/com/google/android/gms/fitness/service/recording/FitRecordingBroker.kt
- play-services-fitness/core/src/main/kotlin/com/google/android/gms/fitness/service/sessions/FitSessionsBroker.kt
- play-services-fitness/core/src/main/kotlin/extensions.kt
- play-services-fitness/src/main/aidl/com/google/android/gms/fitness/internal/IGoogleFitRecordingApi.aidl
- play-services-fitness/src/main/aidl/com/google/android/gms/fitness/internal/IListSubscriptionsCallback.aidl
- play-services-fitness/src/main/aidl/com/google/android/gms/fitness/request/ListSubscriptionsRequest.aidl
- play-services-fitness/src/main/aidl/com/google/android/gms/fitness/request/SubscribeRequest.aidl
- play-services-fitness/src/main/aidl/com/google/android/gms/fitness/request/UnsubscribeRequest.aidl
- play-services-fitness/src/main/aidl/com/google/android/gms/fitness/result/ListSubscriptionsResult.aidl
- play-services-fitness/src/main/java/com/google/android/gms/fitness/data/Subscription.java
- play-services-fitness/src/main/java/com/google/android/gms/fitness/request/ListSubscriptionsRequest.java
- play-services-fitness/src/main/java/com/google/android/gms/fitness/request/SubscribeRequest.java
- play-services-fitness/src/main/java/com/google/android/gms/fitness/request/UnsubscribeRequest.java
- play-services-fitness/src/main/java/com/google/android/gms/fitness/result/ListSubscriptionsResult.java
Added an empty service for the Fitness-related RecordingApi. Some applications rely on this service to make function judgments. Currently, the problem of repeated pop-up windows for application login has been solved.
e.g. com.omicron.adimpara
> Fitness: Add RecordingApi dummy

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
- play-services-maps/core/mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt
When using Mister D <rs.mrdonesi.mobile>, I found that it crashed when adding an address. The reason is that the application uses TransitionManager for transition animation processing, and Mapview's involvement will cause problems, so I have dealt with it here.
> Maps: Fixed a crash caused by transition animation

- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/extensions.kt
- play-services-core/src/main/kotlin/org/microg/gms/games/GamesConnectService.kt
- play-services-core/src/main/kotlin/org/microg/gms/games/GamesSignInActivity.kt
- play-services-core/src/main/kotlin/org/microg/gms/games/extensions.kt
Fixed the issue that the unauthorized account could not log in to the application normally.
e.g. Among Us <com.innersloth.spacemafia> eFootball™ <jp.konami.pesam>
> Auth: Fixed the authorization issue

- vending-app/src/main/kotlin/com/google/android/finsky/IntegrityExtensions.kt
- vending-app/src/main/kotlin/com/google/android/finsky/expressintegrityservice/ExpressIntegrityService.kt
java.security.ProviderException: Failed to generate key pair.
at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPairHelper(AndroidKeyStoreKeyPairGeneratorSpi.java:620)
at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:545)
at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
> PI: Fix Failed to generate key pair and related crashes

- play-services-auth/src/main/aidl/com/google/android/gms/auth/api/identity/AuthorizationRequest.aidl
- play-services-auth/src/main/aidl/com/google/android/gms/auth/api/identity/AuthorizationResult.aidl
- play-services-auth/src/main/aidl/com/google/android/gms/auth/api/identity/VerifyWithGoogleRequest.aidl
- play-services-auth/src/main/aidl/com/google/android/gms/auth/api/identity/VerifyWithGoogleResult.aidl
- play-services-auth/src/main/aidl/com/google/android/gms/auth/api/identity/internal/IAuthorizationCallback.aidl
- play-services-auth/src/main/aidl/com/google/android/gms/auth/api/identity/internal/IAuthorizationService.aidl
- play-services-auth/src/main/aidl/com/google/android/gms/auth/api/identity/internal/IVerifyWithGoogleCallback.aidl
- play-services-auth/src/main/java/com/google/android/gms/auth/api/identity/AuthorizationRequest.java
- play-services-auth/src/main/java/com/google/android/gms/auth/api/identity/AuthorizationResult.java
- play-services-auth/src/main/java/com/google/android/gms/auth/api/identity/VerifyWithGoogleRequest.java
- play-services-auth/src/main/java/com/google/android/gms/auth/api/identity/VerifyWithGoogleResult.java
- play-services-base/src/main/java/com/google/android/gms/auth/api/signin/GoogleSignInOptions.java
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/org/microg/gms/auth/credentials/CredentialsService.kt
- play-services-core/src/main/kotlin/org/microg/gms/auth/credentials/identity/AuthorizationService.kt
Supplementing this service can solve the problem that the application cannot log in normally.
e.g. BTS Island: In the SEOM Puzzle <com.hybeim.intheseom>
> Auth: Add implementation of AuthorizationService

- play-services-auth-workaccount/core/src/main/AndroidManifest.xml
* This is causing them not to be granted at all on newer devices, _potentially_ leading to issues.
* They're already declared in play-services-core as well.
Bug: #2868
> play-services-auth-workaccount: Remove maxSdkVersion from perms

- vending-app/src/main/kotlin/com/google/android/finsky/integrityservice/IntegrityService.kt
- vending-app/src/main/proto/Integrity.proto
Field 6 in IntegrityParams is the cloud project number. 
Adding this to the request may fix issues like https://github.com/microg/GmsCore/issues/2832 where FirebaseAppCheck is used, which in turn passes a cloud project number to the request.
> Integrity: Add cloudProjectNumber to IntegrityParams

- play-services-tapandpay/core/src/main/kotlin/org/microg/gms/tapandpay/TapAndPayService.kt
- play-services-tapandpay/src/main/aidl/com/google/android/gms/tapandpay/internal/ITapAndPayService.aidl
Fix the issue where Bradesco shows a white screen after confirming the card number input.
app name:Bradesco 
package name:com.bradesco
Steps to reproduce:
1. Open Bradesco
2. Enter card number
3. Tap confirm
→ The app navigates to a white screen instead of proceeding normally.
> TapAndPay: Add getActiveWalletId dummy

- play-services-fido/core/src/main/kotlin/org/microg/gms/fido/core/transport/nfc/NfcTransportHandler.kt
- play-services-fido/core/src/main/kotlin/org/microg/gms/fido/core/transport/usb/UsbDevicePermissionManager.kt
- play-services-fido/core/src/main/kotlin/org/microg/gms/fido/core/transport/usb/UsbTransportHandler.kt
If we use fido-core with targetSdk=35, using NFC fails with `Background activity launch blocked!`
This is because starting with SDK35, either the creator or the sender of the pendingIntent need to allow background activity launch (cf https://developer.android.com/guide/components/activities/background-starts#opt-in-required)
> Fido: fix support when targetSdk>=35

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
Some apps crashed because some map controls were missing or not added to the parent layout properly.
e.g. de.hafas.android.db ,  com.yelp.android ,  com.didiglobal.passenger
> HMS Maps: Add fake widgets for better compatibility

- vending-app/src/main/AndroidManifest.xml
- vending-app/src/main/res/values-zh-rCN/strings.xml
- vending-app/src/main/res/values-zh-rTW/strings.xml
- vending-app/src/main/res/values/strings.xml
Issue: Mortal Kombat is stuck on the loading screen.
app name:Mortal Kombat
package name:com.wb.goog.mkx
> add iap permission

- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/GoogleMap.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/MapFragment.kt
- play-services-maps/core/hms/src/main/kotlin/org/microg/gms/maps/hms/Projection.kt
1. Optimize map lag, such as severe route drift when using Uber.
2. Using MapFragment displays abnormally after switching pages.
3. Use TextureMapView by default.
> HMSMap: Improve compatibility

- play-services-base/core/src/main/java/org/microg/gms/auth/AuthRequest.java
- play-services-core/src/main/kotlin/org/microg/gms/auth/credentials/identity/IdentitySignInService.kt
- play-services-core/src/main/kotlin/org/microg/gms/auth/signin/extensions.kt
1. Parameter abnormality cause Login crash. 
2. The authorization domain of IdentitySignInService does not match the authorization domain of AuthorizationService, resulting in a login failure. <com.yahoo.mobile.client.android.finance>
> Fix app crash caused 

- play-services-core/src/main/java/org/microg/gms/auth/AuthManagerServiceImpl.java
- play-services-core/src/main/kotlin/org/microg/gms/phenotype/PhenotypeService.kt
- play-services-core/src/main/kotlin/org/microg/gms/phenotype/extensions.kt
Added Phenotype configuration to use Gemini related functions in Gmail menu bar.
The requestGoogleAccountsAccess method needs to be adapted.
> Phenotype: About using Gemini in Gmail

- play-services-api/src/main/aidl/com/google/android/gms/maps/auth/IApiTokenService.aidl
- play-services-core-proto/src/main/proto/apitoken.proto
- play-services-core/src/main/AndroidManifest.xml
- play-services-core/src/main/kotlin/com/google/android/gms/maps/auth/ApiTokenService.kt
Test application inDrive <sinet.startup.inDriver>, the home page does not display map content after running.
> MapsAuth: Implemented ApiTokenService

- play-services-core/src/main/kotlin/org/microg/gms/phenotype/PhenotypeService.kt
Added new configuration parameters to solve the problem of speech not displaying content in Gboard handwriting mode.
> Phenotype: GBoard: set enable_voice_in_handwriting

- play-services-location/core/provider/src/main/kotlin/org/microg/gms/location/network/wifi/MovingWifiHelper.kt
The old position endpoint does not work anymore.
I don't know if the other TGVs also run this new onboard system, so I have only moved the TGV Lyria provider over.
> Location: Implement TGV Lyria's new position provider

- vending-app/src/main/kotlin/com/google/android/finsky/IntegrityExtensions.kt
- vending-app/src/main/kotlin/com/google/android/finsky/expressintegrityservice/ExpressIntegrityService.kt
Solve the problem of error message after long chatgpt chat.
> PI: Add clientKey refresh timing

- play-services-core/microg-ui-tools/src/main/res/values-fil/strings.xml
These were previously missing, as I didn't know that this component was the one that contained the self-check texts and some parts of the about page. This time they're here now.
> microg-ui-tools: Add Filipino strings
